- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug: 
     msg: "Hello {{ persons }}"

  - names: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer:Sivasir
  ansible.builtin.debug:
    msg: "Course info: {{ course | dict2items }}"